apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev  
spec:
  type: NodePort
  selector:
    app: playground
  ports:
    - port: 80     
      targetPort: 8888 
      nodePort: 30080
